export const metadata = {
  title: 'Bablu Kumar',
  description: 'Generated by Next.js',
  
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body>{children}</body>
    </html>
  )
}
